
[[main]]
    # Top-level menu entry
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1

[[main]]
    # Top-level menu entry
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 2

[[main]]
    # Top-level menu entry
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3
