### SEO, Analytics & 3rd-party
netlify_forms = false # add data-netlify attribute to contact and newsletter forms, false to disable Netlify forms
# gtm_id = '' # GTM tracking (leave blank to use GA)
disallow_search_engines = false # Disallow search engine crawling in robots.txt

### Content
favicon = true # Enable favicon, add your favicon files to /static/ directory
avatar = 'moonscope-header.png' # Custom avatar image in /assets/
grayscale_avatar = false # Add a grayscale filter to the avatar image
author = 'Priyansh Bajaj' # Default author for <head> meta
description = "Personal blog and portfolio site of Priyansh Bajaj." # Add a global meta description to <head>
footer_text = "All rights reserved." # Customize footer text
fallback_text = "No content available yet. Coming soon." # Fallback text for empty content
label_drafts = true # Add a label indicator next to the title of any built drafts (dev only)

# Customize newsletter text
newsletter_header = "Get the Latest Cybersecurity Updates"
newsletter_description = "Receive notifications from Moonscope Security for the latest cybersecurity guides, insightful posts, and valuable resources."
newsletter_submit = "Join Telegram Channel"
telegram_link = "https://t.me/MoonscopeSecurity"
global_newsletter = false # Enable newsletter site-wide

# CSS / JavaScript
enable_postcss = false # Enable if you're using npm and want to utilize PostCSS processing
custom_css = 'custom.css' # Add the specified file to assets before setting this param to avoid errors
custom_js = 'custom.js' # Add the specified file to assets before setting this param to avoid errors

### Web schemas
# Open Graph
images = ['images/default.png'] # Fallback for Open Graph and Twitter Cards images if none are present in front matter. Enter path to the image.
ogLocale = "en_US" # Open graph locale

# Twitter Cards
twitterSite = "" # Enter your twitter handle without the @
twitterCreator = "" # Enter your twitter handle without the @

# JSON-LD structured data schemas
schemaName = "Priyansh Bajaj" # Enter your name
schemaLocale = "en-US" # Structured data locale
schemaImage = "images/default.png" # Image for Person structured data schema. Enter path to the image.
schemaImageWidth = 453 # Width of the above image
schemaImageHeight = 455 # Height of the above image

### Social
# Show social links in footer, home hero section, or about page
footer_socials = false
home_hero_socials = false
about_page_socials = true

# Enable or disable individual social icons
[social.links]
  # twitter = "username"
  # github = "username"
  # stack_overflow = "userid/username" # include user id
  # email = "user@example.com"
  linkedin = "priyansh-bajaj" # Comment out to disable
  # mastodon_server = "example.social" # include subdomains if relevant, scheme not needed (defaults to https)
  # mastodon_user = "username" # don't include preceding @

# Enable or disable individual social share icons in posts
[social.share]
  facebook = false
  linkedin = true
  twitter = false
  reddit = false
  email = true
